### ISSUE TITLE
retrieving by name does not work for non-Default keyrings

### ISSUE THREAD

**Issue by chicks-net** [kparal/gkeyring#9]
I can add a password to the keychain with a given name, but then I can't retrieve it with the same name.

```
$ gkeyring --set --name test_gkeyring --keyring graphs_life
Password: 
6
$ gkeyring --keyring graphs_life --n test_gkeyring
$ gkeyring --keyring graphs_life --name=test_gkeyring
$ gkeyring --keyring graphs_life --id=6
6       test_gkeyring   foobar
```

`id` works fine, but `name` does not return anything.  I'm running the latest version from your github repo.

**Comment by kparal** [comment]
Thanks for reporting. Patches welcome.

**Comment by chicks-net** [comment]
Any suggestions on how to debug it?

**Comment by joergschulz** [comment]
There is a bug that might trigger this if you have a key with the same name `test_gkeyring` in another keyring. `gk.find_items()` returns items from *any* keyring. But `gk.item_get_info()` is called with keyring from `--keyring` argument. If this key doesn't exist a BadArgumentError is thrown and the for-loop silently aborts. So line 269 has to be:

```
-                    info = gk.item_get_info_sync(self.keyring, match.item_id)
+                    info = gk.item_get_info_sync(match.keyring, match.item_id)
```
And the program should at least print an error:
```
-        except gk.Error:
+        except gk.Error as e:
+            print e.__class__, e.message
```
From your usage of the program above
```$ gkeyring --keyring graphs_life --n test_gkeyring```
one can conclude that you expect that the `--keyring` argument is a kind of selector.
But this is only true if you use it in combination with the `--id` argument.
To use it as an selector you could write:
```
                 for match in matches:
+                    if match.keyring != self.keyring:
+                        continue
                     result = {'id': match.item_id, 'secret': match.secret,
```
If you use it this way maybe it woud be better to allow an undefined keyring in option parsing instead of using the default keyring.

**Comment by kparal** [comment]
Hi, can you create a pull request? Thanks.

**Comment by kparal** [comment]
@chicks-net Could work now.
